### PR TITLE
Update to 1.4.1 release of origin

### PR DESCRIPTION
**Pull request by tmckayus**
Includes results of "gofmt -w". Modify the code to work against
origin 1.4.1. The major change here is that scaling must be
done against the deploymentconfig and not the replication
controller.

### CODE REVIEW

**Comment by elmiko** [comment]
this worked for me from the rest build, but i'm not sure about the travis tests here. were they ever working?

**Comment by elmiko** [comment]
tested through both -cli and -rest, everything worked.

**Comment by crobby** [comment]
I'm pretty sure that the travis tests have never worked.  There isn't even a .travis.yml defined.  Are there tests that could be run?  It would be a pretty simple .travis.yml, most likley.

**Comment by tmckayus** [comment]
Yeah, travis has never been fixed up.  Hardly worth it at this point if we're going to merge repos.

**Pull request merged**
